
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hotel
{

using System;
    using System.Collections.Generic;
    
public partial class Hotel
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Hotel()
    {

        this.Dobavljac = new HashSet<Dobavljac>();

        this.Korisnik = new HashSet<Korisnik>();

        this.Soba = new HashSet<Soba>();

        this.Rezervacija = new HashSet<Rezervacija>();

        this.Gost = new HashSet<Gost>();

    }


    public int ID_hotel { get; set; }

    public string Ime { get; set; }

    public string Adresa { get; set; }

    public string Telefon { get; set; }

    public string Email { get; set; }

    public string Drzava { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Dobavljac> Dobavljac { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Korisnik> Korisnik { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Soba> Soba { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Rezervacija> Rezervacija { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Gost> Gost { get; set; }

}

}
