
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hotel
{

using System;
    using System.Collections.Generic;
    
public partial class Korisnik
{

    public int ID_korisnik { get; set; }

    public string Ime { get; set; }

    public string Prezime { get; set; }

    public string OIB { get; set; }

    public string Adresa { get; set; }

    public string Telefon { get; set; }

    public string Email { get; set; }

    public string Lozinka { get; set; }

    public string Korisnicko_ime { get; set; }

    public System.DateTime Datum_zaposlenja { get; set; }

    public int ID_hotela { get; set; }

    public int ID_strucne_spreme { get; set; }

    public int ID_vrste_korisnika { get; set; }



    public virtual Hotel Hotel { get; set; }

    public virtual StrucnaSprema StrucnaSprema { get; set; }

    public virtual VrstaKorisnika VrstaKorisnika1 { get; set; }

}

}
