

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hotel
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class PI20_021_DBEntities2 : DbContext
{
    public PI20_021_DBEntities2()
        : base("name=PI20_021_DBEntities2")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Dobavljac> Dobavljac { get; set; }

    public virtual DbSet<Gost> Gost { get; set; }

    public virtual DbSet<Hotel> Hotel { get; set; }

    public virtual DbSet<Korisnik> Korisnik { get; set; }

    public virtual DbSet<Racun> Racun { get; set; }

    public virtual DbSet<Rezervacija> Rezervacija { get; set; }

    public virtual DbSet<Soba> Soba { get; set; }

    public virtual DbSet<StrucnaSprema> StrucnaSprema { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<Usluga> Usluga { get; set; }

    public virtual DbSet<VrstaGosta> VrstaGosta { get; set; }

    public virtual DbSet<VrstaKorisnika> VrstaKorisnika { get; set; }

    public virtual DbSet<VrstaRezervacije> VrstaRezervacije { get; set; }

    public virtual DbSet<VrstaSobe> VrstaSobe { get; set; }

}

}

