
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hotel
{

using System;
    using System.Collections.Generic;
    
public partial class Racun
{

    public int ID_racun { get; set; }

    public System.DateTime Datum { get; set; }

    public double Ukupan_iznos { get; set; }

    public string Nacin_placanja { get; set; }

    public bool Placen { get; set; }

    public int ID_rezervacije { get; set; }

    public int ID_sobe { get; set; }



    public virtual Rezervacija Rezervacija { get; set; }

    public virtual Soba Soba { get; set; }

}

}
