//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StavkaRacuna
    {
        public int ID_racuna { get; set; }
        public int ID_korisnika { get; set; }
        public int ID_gosta { get; set; }
    
        public virtual Gost Gost { get; set; }
        public virtual Korisnik Korisnik { get; set; }
        public virtual Racun Racun { get; set; }
    }
}
